### ISSUE TITLE
Difference to Chrome EC (CrOS EC)

### ISSUE THREAD

**Issue by paulmenzel** [intel/ecfw-zephyr#10]
[Sorry, hit enter by accident too early.]

What is the difference to [Chrome EC](https://chromium.googlesource.com/chromiumos/platform/ec/+/HEAD/README.md), which also moved to Zephyr some time ago?

**Comment by albertofloyd** [comment]
@paulmenzel This reference code is intended for platforms running Windows OS and showcase interaction with Intel BIOS.

**Comment by paulmenzel** [comment]
But you are aware of the Chrome EC? They also switched to Zephyr, and their code is battle tested on million devices (Google Chromebooks). Are you in contact with them?

**Comment by albertofloyd** [comment]
@paulmenzel 
Yes, we are well aware.  As pointed out the code intentions & targets are different.

If you additional specific questions in the any of these pointed differences, feel to add details to another question
