### ISSUE TITLE
Intel ADL RVP MEC Model

### ISSUE THREAD

**Issue by LeanSheng** [intel/ecfw-zephyr#11]
Hi good day, may I know why the MEC uploaded here is MEC1501 while the Intel ADL RVP is using MEC1521? Does this (MEC1501) works on RVP?
Thanks.

**Comment by albertofloyd** [comment]
Yes, this code works in MEC1521 too. 
You just need to use different SPI image generator. 

Refer to  https://github.com/zephyrproject-rtos/zephyr/blob/main/boards/arm/mec1501modular_assy6885/CMakeLists.txt#L12

**Comment by LeanSheng** [comment]
got it thanks Albert!
