### ISSUE TITLE
The Intel EC doc is not updated to the latest Intel EC version

### ISSUE THREAD

**Issue by LeanSheng** [intel/ecfw-zephyr#19]
In the doc, https://intel.github.io/ecfw-zephyr/reference/getting_started.html, "EC FW Open source 1.50 project is based on Zephyr v2.5 so need to refer to Zephyr v2.5 documentation and use Zephyr SDK 0.12.2." it is still based on Zephyr v2.5 instead of v2.7.

**Comment by LeanSheng** [comment]
@rgundi

**Comment by rgundi** [comment]
@LeanSheng, this will be addressed in the next release of OpenEC due shortly.

**Comment by albertofloyd** [comment]
@LeanSheng closing since current code is based on 2.7
