### ISSUE TITLE
MEC1428 support

### ISSUE THREAD

**Issue by beachmiles** [intel/ecfw-zephyr#24]
Skylake and TigerLake Intel RVP boards use the MEC1428, I dont see any mention of the MEC1428 here. I am having a heck of a time finding the source for this RVP as I need to add some additional features. Intel only provides a compiled MEC1428 EC firmware but no source.
Intel and Microchip tech support are not helping me out much at all. 
Would the better move be to skip the MEC1428 chip and use the MEC1501 or MEC172x which appear to be supported with Intel source code provided in this repo.

Thanks!

**Comment by albertofloyd** [comment]
Intel basic EC FW open source framework is not same source code used to generate the EC FW for Intel RVP.
The open source provided a subset of features. Refer to https://intel.github.io/ecfw-zephyr/reference/overview.html 

Skylake and tigerlake didn't use Zephyr-based EC FW so there is no plan to add support for that in this project.

For any new designs intending to use this project as reference recommendation is to use MEC152x and MEC172x. Refer to https://intel.github.io/ecfw-zephyr/reference/supported_hw.html

**Comment by beachmiles** [comment]
> Skylake and tigerlake didn't use Zephyr-based EC FW so there is no plan to add support for that in this project.

It looks like the MEC15xx has this config switch for TigerLake "CONFIG_MEC15XX_AIC_ON_TGL"
https://github.com/intel/ecfw-zephyr/blob/a324501d1e32a317330ad0e2922d3a7d5b3ccbf0/boards/microchip/mec15xx_mecc/mec15xx_aic_rvp_selection.h#L16

It references this file so maybe there is TigerLake support?
https://github.com/intel/ecfw-zephyr/blob/a324501d1e32a317330ad0e2922d3a7d5b3ccbf0/boards/microchip/mec15xx_mecc/tgl_mec1501.h#L4

**Comment by albertofloyd** [comment]
No, ICL/TGL RVP have MEC1428 soldered down on the motherboard. There is no Intel Basic EC Open source support for that.

The files mentioned are to support TGL RVP + MEC152x MECC card setup, in such case the MEC1428 is disabled and the EC used is the one from add-on card.
https://docs.zephyrproject.org/latest/boards/arm/mec1501modular_assy6885/doc/index.html

**Comment by beachmiles** [comment]
@albertofloyd Thanks, I am trying to build a case to not use the MEC1428 and instead use the MEC15xx for our new tiger lake design.
It sounds like zephyr supports the "TGL RVP + MEC152x MECC card setup" so I think this seems like the way to go.
We have been waiting for a TGL RVP platform from Intel for a few months now and I have had not too much luck with the MECC1428 dev board in standalone mode.
