### ISSUE TITLE
ecfw-zephry FATAL ERROR ....

### ISSUE THREAD

**Issue by rosslu2002** [intel/ecfw-zephyr#36]
Hello, Members..

I try to download code from Zephyr EC git hub, but i got some problem for west list command and west upadte commnad.

c:\Workspace\Test\ZephyrEC1_5>mkdir sandbox

c:\Workspace\Test\ZephyrEC1_5>cd sandbox

c:\Workspace\Test\ZephyrEC1_5\sandbox>git clone https://github.com/intel/ecfw-zephyr
Cloning into 'ecfw-zephyr'...
remote: Enumerating objects: 1088, done.
remote: Counting objects: 100% (197/197), done.
remote: Compressing objects: 100% (90/90), done.
remote: Total 1088 (delta 138), reused 108 (delta 107), pack-reused 891
Receiving objects: 100% (1088/1088), 9.42 MiB | 9.09 MiB/s, done.

Resolving deltas: 100% (608/608), done.
Updating files: 100% (320/320), done.

c:\Workspace\Test\ZephyrEC1_5\sandbox>cd ecfw-zephyr

c:\Workspace\Test\ZephyrEC1_5\sandbox\ecfw-zephyr>west init -l
=== Initializing from existing manifest repository ecfw-zephyr
--- Creating C:\Workspace\Test\ZephyrEC1_5\sandbox\.west and local configuration file
=== Initialized. Now run "west update" inside C:\Workspace\Test\ZephyrEC1_5\sandbox.

c:\Workspace\Test\ZephyrEC1_5\sandbox\ecfw-zephyr>west list
FATAL ERROR: can't load west manifest: Malformed manifest file: c:\Workspace\Test\ZephyrEC1_5\sandbox\ecfw-zephyr\west.yml
Schema file: C:\Python310\lib\site-packages\west\manifest-schema.yml
Hint: default remote github_restricted is not defined

c:\Workspace\Test\ZephyrEC1_5\sandbox\ecfw-zephyr>west update
FATAL ERROR: Malformed manifest file: C:\Workspace\Test\ZephyrEC1_5\sandbox\ecfw-zephyr\west.yml
  Schema file: C:\Python310\lib\site-packages\west\manifest-schema.yml
  Hint: default remote github_restricted is not defined

How can i do next???

Ross
![WestUpdateFATAL_ERROR](https://github.com/intel/ecfw-zephyr/assets/9209355/156bdf78-2e83-4a79-aba0-e0ed5c45a427)

**Comment by make0104** [comment]
it seems the latest change on west.yml got typo.
changing remote project from "github_restricted" to "zephyrproject" would be effective.
