### ISSUE TITLE
Missing files compared to the list Intel is distributing with the EC FW binary (Intel Kit 643307).

### ISSUE THREAD

**Issue by lweight-intel** [intel/ecfw-zephyr#4]
Hello!

Any assistance would be much appreciated.

There is currently a disparity between files used in this repo and those found in the binary provided by Intel. It seems there may have been an update that has not filtered through to GitHub. In trying to rebuild the binary using this repo code for board validation, we've found it cannot be rebuilt due to this disparity.

I have attached files with the differences below.

[FileListGithub (2).txt](https://github.com/intel/ecfw-zephyr/files/6847570/FileListGithub.2.txt)

Thanks for your help.

**Comment by albertofloyd** [comment]
Hi, 

Zephyr-EC FW source code in this repo  is a select subset of features from EC FW binary distributed in Intel Kits.

The code is in this repo is tailored for evaluation purposes of power sequencing and control of few peripherals only in current supported HW (TGL + MECC) as indicated in the documentation

ADL board minimum board support will be added soon, also some additional features, but none of the updates will match the entire feature list from Intel kits.

**Comment by lweight-intel** [comment]
Thanks for your help. I have found through the documentation with your help what parts of the EC FW are intended for open-source now. I will pass this information on to the relevant parties.
